bump tailwind to v3.3.3
phoenixframework/tailwind pull request #91
Opened 2023-08-15 18:20 UTC by voxxal

2024-04-23 10:42 UTC, 03juan requested changes

2024-04-23 10:42 UTC, 03juan commented on lib/tailwind.ex
> +  @latest_version "3.3.3"
Current latest version 👍

2024-12-06 14:16 UTC, glhrmv commented
This looks obsolete now with #103 @josevalim

2024-12-11 19:19 UTC, voxxal commented
Yes, looks like this is superseded by #103,

2024-12-11 19:19 UTC, closed without merging